try:
  import unzip_requirements
except ImportError:
  pass


import json
import boto3
import base64
import string
import random
        
def select_server():
    servers = 'abc'
    return random.choice(servers)

def get_redirect(z, x, y):
    response = {
        "statusCode": 302,
        "headers": {'Location': 'https://' +
                                select_server() +
                                '.tile.openstreetmap.org/' +
                                z + '/' +
                                x + '/' +
                                y}
    }
    return response

def get_tile(z, x, y):
    body = "iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAADYklEQVR4nO3UMWrDUBBAQZ/bKXUD3UKVA+q+DiPfRKlcxIFg3BjxpphmYWGbfZf7vh9A0+XTBwCfIwAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgAQJgBwctsYb+8KAJzUNsYxTdMxz/Ov+bIsx9f1+lIYBABO6vHgzwHYxjjWdRUAKHgOwH3fBQAqBADCBADCBADCvm+3P7NtDAEA/icAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAECYAEPYDw8wlgMsU1kgAAAAASUVORK5CYII="

    response =  {
        "isBase64Encoded": True,
        "statusCode": 200,
        "headers": {
            "Content-Type": "image/png",
        },
        "body": body
    }
    return response

def wmtsHandler(event, context):
    z = event['pathParameters']['z']
    x = event['pathParameters']['x']
    y = event['pathParameters']['y']

    response = get_tile(z, x, y)
    return response












